# This is a basic workflow to help you get started with Actions
name: Security

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # and when files are altered in the github workflow directory
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'

jobs:
  # This workflow contains a single job that fails if called
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: A/B Check
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Altering CI is not permitted!')
